### ISSUE TITLE
Stream: PassThrough?

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/simple-html-index#2]
Should this be using PassThrough instead of through2? Is there any significant gain?

https://github.com/scottcorgan/tap-out/pull/11
/cc @shinnn

**Comment by shinnn** [comment]
Here is my opinion: https://github.com/scottcorgan/tap-out/pull/11#issuecomment-112890993

On the other hand, someone still prefer through2 for its simplicity: https://github.com/kevva/vinyl-assign/pull/1#issuecomment-113893735

https://github.com/kevva/vinyl-assign/pull/1#issuecomment-113897384

> Streams3 has a [simplified constructor API](https://iojs.org/api/stream.html#stream_simplified_constructor_api) (https://github.com/nodejs/readable-stream/issues/102) and we can use it everywhere by using readable-stream v2.0.0. That seems enough simple for me and I think now through2 is almost finishing its roles in the point of simplicity.

https://github.com/kevva/vinyl-assign/pull/1#issuecomment-113897532

> I'm aware, but `through2` still have a tiny bit simpler API, so I don't really see the benefit of switching.

**Comment by shinnn** [comment]
> Is there any significant gain?

Package file size is slightly different.

```
$ npm i through2
$ du -sh node_modules/through2
> 364K  node_modules/through2
```

```
$ npm i readable-stream
$ du -sh node_modules/readable-stream
> 304K  node_modules/readable-stream
```

**Comment by yoshuawuyts** [comment]
For correctness: shouldn't this be a `ReadableStream` rather than a `TransformStream`? We're not taking any input; it's output only. Might save some issues with with the predictability of finish events (`.on('finish'|'end')`). [`from2`](https://github.com/hughsk/from2) / [`from2-string`](https://github.com/yoshuawuyts/from2-string) is pretty good for that.

**edit**: for the record: `from2` and friends use `readable-stream` under the hood :tada:

**Comment by mattdesl** [comment]
`from2-string` seems like a better fit for this module than `through2` :smile:

**Comment by shinnn** [comment]
:+1: `from2-string`
